//Form Candidate
export const HANDLE_INPUT = "HANDLE_INPUT";
export const HANDLE_EXPERIENCE = "HANDLE_EXPERIENCE";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const REMOVE_EXPERIENCE = "REMOVE_EXPERIENCE";
export const ADD_TRAINING = "ADD_TRAINING";
export const HANDLE_TRAINING = "HANDLE_TRAINING";
export const REMOVE_TRAINING = "REMOVE_TRAINING";
export const ADD_LANGUAGE = "ADD_LANGUAGE";
export const HANDLE_LANGUAGE = "HANDLE_LANGUAGE";
export const REMOVE_LANGUAGE = "REMOVE_LANGUAGE";
export const ADD_ABILITY = "ADD_ABILITY";
export const HANDLE_ABILITY = "HANDLE_ABILITY";
export const REMOVE_ABILITY = "REMOVE_ABILITY";
export const IS_EDITABLE = "IS_EDITABLE";
export const IS_NOT_EDITABLE = "IS_NOT_EDITABLE";

//Profile
export const SET_PROFILE = "SET_PROFILE";
export const HANDLE_INPUT_PROFILE = "HANDLE_INPUT_PROFILE";
export const HANDLE_EXPERIENCE_PROFILE = "HANDLE_EXPERIENCE_PROFILE;"
export const ADD_PROFILE_TRAINING = "ADD_PROFILE_TRAINING";
export const REMOVE_PROFILE_TRAINING = "REMOVE_PROFILE_TRAINING";
export const ADD_PROFILE_EXPERIENCE = "ADD_PROFILE_EXPERIENCE";
export const REMOVE_PROFILE_EXPERIENCE = "REMOVE_PROFILE_EXPERIENCE";
export const HANDLE_TRAINING_PROFILE = "HANDLE_TRAINING_PROFILE";
export const HANDLE_LANGUAGE_PROFILE = "HANDLE_LANGUAGE_PROFILE"
export const REMOVE_LANGUAGE_PROFILE = "REMOVE_LANGUAGE_PROFILE"
export const ADD_LANGUAGE_PROFILE = "ADD_LANGUAGE_PROFILE"
export const HANDLE_ABILITY_PROFILE = "HANDLE_ABILITY_PROFILE"
export const ADD_ABILITY_PROFILE = "ADD_ABILITY_PROFILE"
export const REMOVE_ABILITY_PROFILE = "REMOVE_ABILITY_PROFILE";
//Form Company
export const HANDLE_INPUT_COMPANY = "HANDLE_INPUT_COMPANY";

//Popup
export const SHOW_POPUP = "SHOW_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";
//Error
export const SET_ERROR = "SET_ERROR"
//User
export const USER_LOGOUT = "USER_LOGOUT";