export const HANDLE_INPUT = "HANDLE_INPUT";
export const HANDLE_EXPERIENCE = "HANDLE_EXPERIENCE";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const REMOVE_EXPERIENCE = "REMOVE_EXPERIENCE";
export const ADD_TRAINING = "ADD_TRAINING";
export const HANDLE_TRAINING = "HANDLE_TRAINING";
export const REMOVE_TRAINING = "REMOVE_TRAINING";