//Form
export const HANDLE_INPUT = "HANDLE_INPUT";
export const HANDLE_EXPERIENCE = "HANDLE_EXPERIENCE";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const REMOVE_EXPERIENCE = "REMOVE_EXPERIENCE";
export const ADD_TRAINING = "ADD_TRAINING";
export const HANDLE_TRAINING = "HANDLE_TRAINING";
export const REMOVE_TRAINING = "REMOVE_TRAINING";
export const ADD_LANGUAGE = "ADD_LANGUAGE";
export const HANDLE_LANGUAGE = "HANDLE_LANGUAGE";
export const REMOVE_LANGUAGE = "REMOVE_LANGUAGE";
export const ADD_ABILITY = "ADD_ABILITY";
export const HANDLE_ABILITY = "HANDLE_ABILITY";
export const REMOVE_ABILITY = "REMOVE_ABILITY";
//Popup
export const SHOW_POPUP = "SHOW_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";
//Error
export const SET_ERROR = "SET_ERROR"
//User
export const USER_LOGOUT = "USER_LOGOUT";